services:
  - type: web
    name: transkrib-bot
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y ffmpeg git build-essential && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: <TOKEN>
      - key: PYTHON_VERSION
        value: 3.10
